
name: Docker Image CI
'on':
  push:
    branches:
      - main
env:
    DOCKER_USERNAME: ctrlpy
    DOCKER_REPOSITORY_NAME: node-server
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install -g semantic-release @semantic-release/exec semantic-release-plus @semantic-release-plus/docker
      - run: npm run semantic-release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}