name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with: 
          node-version: 16.x
    - run: npm install -g semantic-release @semantic-release/exec semantic-release-plus @semantic-release-plus/docker
    - run: semantic-release
             
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
          image: ctrlpy/node-server
          registry: docker.io
         
     
